# Fichier de configuration wrangler.toml pour Cloudflare Pages
name = "festiveambience"
main = "_worker.js"
compatibility_date = "2025-03-05"

# Définir le dossier de sortie pour Cloudflare Pages
pages_build_output_dir = "out"

[site]
bucket = "out" 